version: '3.8'

services:
  backend:
    build: ./tg_bot/backend
    ports:
      - "8000:8000"
    env_file:
      - tg_bot/.env

  bot:
    build: ./tg_bot/bot
    env_file:
      - tg_bot/.env

  ml:
    build: ./ml
    ports:
      - "8888:8000"
