version: '3.8'

services:
  tg_bot_backend:
  
    build: ./tg_bot/backend
    ports:
      - "88:8000"
    env_file:
      - tg_bot/.env
    volumes:
      - ./tg_bot/backend/app/bd/files:/app/bd/files

  ml:
    build: ./ml
    ports:
      - "8887:8000"
    env_file:
      - ml/.env
    networks:
      - back-network
    volumes:
      - ./ml/app:/app
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_HOST_HTTP=http://134.122.58.32:8080/
      # - VITE_API_HOST_HTTP=http://netback:80/
    networks:
      - back-network

  netback:
    image: bpla:0.0.22
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    volumes:
      - "/home/config/appsettings.json:/app/appsettings.json"
    networks:
      - back-network
  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Bpla100624_pong"
    volumes:
      - "/home/data:/var/lib/postgresql/data"
    ports:
      - "16543:5432"
    networks:
      - back-network


  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "19000:9000"
      - "19001:9001"
    environment: 
      MINIO_ROOT_USER: "ROOT"
      MINIO_ROOT_PASSWORD: "minio_bpla53"
    volumes:
      - "/home/minio:/data"
    command: server --console-address ":9001" /data
    networks:
      - back-network

networks:
  back-network:
    driver: bridge
